config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels
  validates :title, presence: true
  validates :content, presence: true
  validates :expired_at, presence: true
  validates :status, presence: true
  validates :user_id, presence: true
  scope :search_title, -> (search_title) { where("title LIKE ?", "%#{search_title}%") }
  scope :search_status, -> (search_status) { where(status: search_status)}
  scope :search_label, -> (search_label) { joins(:labels).where(labels: { id: search_label })}
  enum status: { 未着手: 1, 着手: 2, 完了: 3 }
  enum priority: { 高: 1, 中: 2, 低: 3 }
end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  enum admin: { 一般: false, 管理者: true }
  before_destroy :delete_admin
  private
  def delete_admin
    if User.where(admin: true).count == 1 && self.admin == "管理者"
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.select(:id, :name).page(params[:page]).per(3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id), notice: "ユーザー情報を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "ユーザー情報を編集しました"
    else
      render :edit
    end
  end

  def show
    @tasks = @user.tasks.page(params[:page]).per(3)
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice:"ユーザー情報を削除しました"
    else
      redirect_to admin_users_path, notice:"管理者は最低1人必要です。"
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
  end

  def if_not_admin
    redirect_to root_path, notice:"管理画面へは、管理者以外はアクセスできません" unless admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = current_user.tasks
    @tasks = @tasks.order(expired_at: :desc) if params[:sort_expired]
    @tasks = @tasks.order(priority: :asc) if params[:sort_priority]

    if params[:search]
      @tasks = @tasks.search_title(params[:search_title]) if params[:search_title]
      @tasks = @tasks.search_status(params[:search_status]) if params[:search_status] != ""
      @tasks = @tasks.search_label(params[:search_label]) if params[:search_label] != ""

    end

    @tasks = @tasks.page(params[:page]).per(3)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "タスクを作成しました！"
    else
      render :new
    end

  end

  def self.search(search)
    return Product.all unless search
    Product.where(['name LIKE ?', "%#{search}%"])
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました！"
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :expired_at, :status, :priority, :user_id, { label_ids: [] })
  end
  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to tasks_path
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def button_text
    if action_name == "new"
      "新規作成する"
    elsif action_name == "edit"
      "更新する"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    if logged_in?
      current_user.admin == "管理者"
    end
  end
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h3><%= @user.errors.count %>件のエラーがあります。</h3>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [ :admin, @user ], local: true) do |f| %>
  <div class="admin_new_area">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="admin_new_area">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="admin_new_area">
    <%= f.label :password %><br>
    <%= f.password_field :password %>  
  </div>
  <div class="admin_new_area">
    <%= f.label :パスワード確認 %><br>
    <%= f.password_field :password_confirmation %>  
  </div>
  <div class="admin_new_area">
    <%= f.label :admin %><br>
    <%= f.select :admin, User.admins.keys %>  
  </div><br>
  <div class="admin_new_area"><%= f.submit %></div>
<% end %>
<p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to "ユーザー一覧画面にもどる", admin_users_path %></button></p>

app/views/admin/users/edit.html.erb
<h2>【管理画面】ユーザー情報編集</h2>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h2>【管理画面】：ユーザー一覧画面</h2>
<div>
  <p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to '新規ユーザー作成', new_admin_user_path %></button></p>
  <% @users.each do |user| %>
    <hr>
    <p>
      <span class="index_area">名前：<%= user.name %></span>
      <span class="index_area">ID：<%= user.id %></span>
      <span class="index_area">タスク：<%= user.tasks.count %>件</span>
    </p>
    <span type="button" class="btn btn-default btn-sm"><%= link_to '詳細を確認', admin_user_path(user.id), class: "show_user" %></span>
    <span type="button" class="btn btn-default btn-sm"><%= link_to "ユーザー情報を編集", edit_admin_user_path(user.id), data: { confirm: '本当に編集していいですか？' } %></span>
    <span type="button" class="btn btn-default btn-sm"><%= link_to 'ユーザー情報を削除', admin_user_path(user.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></span>
  <% end %>
  <hr>
</div>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<h2>【管理画面】新規登録</h2>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h2>【管理画面】：ユーザー詳細情報</h2>
<div class="admin_show_area">
	<p>名前：<%= @user.name %></p>
	<p>ID：<%= @user.id %></p>
	<p>メールアドレス：<%= @user.email %></p>
	<p>管理権限：<%= @user.admin == "管理者" ? "あり" : "なし" %></p>
	<% @tasks.each do |task| %>
		<hr>
		<p>タスク名：<%= task.title %></p>
		<p>内容：<%= task.content %></p>
		<p>タスク：<% task.labels.each do |label| %>
              <%= label.name %>
            <% end %>
  	</p>
		<p>登録日時：<%= task.created_at %></p>
		<p>終了期限：<%= task.expired_at %></p>
		<p>ステータス：<%= task.status %></p>
		<p>優先順位：<%= task.priority %></p>
		<span type="button" class="btn btn-default btn-sm"><%= link_to '詳細を確認する', task_path(task.id) %></span>
		<span type="button" class="btn btn-default btn-sm"><%= link_to "タスクを編集する", edit_task_path(task.id), data: { confirm: '本当に編集していいですか？' }, class: "edit_task" %></span>
		<span type="button" class="btn btn-default btn-sm"><%= link_to 'タスクを削除する', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "delete_task" %></span>
	<% end %><br>
</div>
<hr>
<%= paginate @tasks %>
<p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to "ユーザー一覧画面にもどる", admin_users_path %></button></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- コード追加 Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加 Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">タスク管理app</span>
          </div>
          <div class="collapse navbar-collapse" id="navbarEexample1">
            <ul class="nav navbar-nav">
              <li><%= link_to '新規作成', new_task_path %></li>
              <li><%= link_to 'タスク一覧', tasks_path %></li>
              <li><%= link_to "管理画面", admin_users_path %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="content">
      <% flash.each do |key, value| %>
        <div class="message"><%= content_tag(:div, value, class: "#{key}") %></div>
      <% end %>
      <% if logged_in? %>
        <button type="button" class="btn btn-info"><%= link_to "プロフィール", user_path(current_user.id) %></button>
        <button type="button" class="btn btn-warning"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></button> 
      <% else %>
        <button type="button" class="btn btn-info"><%= link_to "新規アカウント作成", new_user_path %></button>
      <% end %>
      <%= yield %>
    </div>   
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new_area">
    <%= form.label :タスク名 %><br>
    <%= form.text_field :title, placeholder: "タスク名を入力", size: 50 %>
  </div>
  <div class="new_area">
    <%= form.label :タスク内容 %><br>
    <%= form.text_area :content, placeholder: "タスク内容を入力", size: "50x5" %>
  </div>
  <div class="new_area">
    <%= form.label :終了期限 %><br>
    <%= form.date_field :expired_at %>
  </div>
  <div class="new_area">
    <%= form.label :ステータス %><br>
    <%= form.select :status,  Task.statuses.keys %>
  </div>
  <div class="new_area">
    <%= form.label :優先順位 %><br>
    <%= form.select :priority,  Task.priorities.keys %>
  </div>
  <div class="new_area">
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>
  <div class="new_area"><%= form.submit button_text %><br>
<% end %>
<p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to '戻る', tasks_path %></button></p>

app/views/tasks/edit.html.erb
<h2>タスクを編集する</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>
<div>
  <%= form_with(local: true, method: :get, url: tasks_path ) do |form| %>
    <p class="search">
      <span class="search_area">
        <%= form.label :search_title, "タスク名" %>
        <%= form.text_field :search_title, placeholder: "タスク名で検索", size: 50 %>
      </span>
      <span class="search_area">
        <%= form.label :search_status, "ステータス" %>
        <%= form.select :search_status, Task.statuses.keys, { include_blank: '選択してください'}, size: 1 %>
      </span>
      <span class="search_area">
        <%= form.label :search_label, "ラベル" %>
        <%= form.select :search_label, Label.pluck(:name, :id), { include_blank: '選択してください' }, size: 1 %></p>
      </span>
      <span class="search_area">
        <%= form.submit "検索", name: "search" %>
      </span>
    </p>
  <% end %>
</div>
<p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to '新規作成', new_task_path %></button></p>
<table>
  <tr>
    <th>作成者</th>
    <th>タスク名</th>
    <th>タスク内容</th>
    <th>ラベル</th>
    <th><%= link_to "終了期限 🔽", tasks_path(sort_expired: "true") %></th>
    <th>ステータス</th>
    <th><%= link_to "優先順位 🔽", tasks_path(sort_priority: "true") %></th>
  </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td class="task_row"><%= task.user.name %></td>
      <td class="task_row"><%= task.title %></td>
      <td class="task_row"><%= task.content %></td>
      <td class="task_row">
        <% task.labels.each do |label| %>
          <%= label.name %>
        <% end %>
      </td>
      <td class="task_row"><%= task.expired_at %></td>
      <td class="task_row"><%= task.status %></td>
      <td class="task_row"><%= task.priority %></td>
      <td type="button" class="btn btn-default btn-sm"><%= link_to '詳細を確認', task_path(task.id) %></td>
      <td type="button" class="btn btn-default btn-sm"><%= link_to 'タスクを編集', edit_task_path(task.id) %></td>
      <td type="button" class="btn btn-default btn-sm"><%= link_to 'タスクを削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }%></td>
    </tr>
  <% end %>
</table>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h2>タスク詳細</h2>
<div class="new_area">
  <p>タスク名：<%= @task.title %></p>
  <p>タスク内容：<%= @task.content %></p>
  <p>タスク：<% @task.labels.each do |label| %>
              <%= label.name %>
            <% end %>
  </p>
  <p>終了期限：<%= @task.expired_at %></p>
  <p>ステータス：<%= @task.status %></p>
  <p>優先順位：<%= @task.priority %></p>
  <% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %> 
  <p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to '戻る', tasks_path %></button></p>
</div>

app/views/users/new.html.erb
<h2>新規アカウント作成</h2>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>  
  <p class="new_area">
    <%= f.label :名前 %><br>
    <%= f.text_field :name %>
  </p>
  <p class="new_area">
   <%= f.label :メールアドレス %><br>
    <%= f.email_field :email %> 
  </p>
  <p class="new_area">
    <%= f.label :パスワード %><br>
    <%= f.password_field :password %>
  </p>
  <p class="new_area">
    <%= f.label :パスワード確認 %><br>
    <%= f.password_field :password_confirmation %>
  </p><br>
  <p class="new_area"><%= f.submit "新規作成" %></p>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %>のページ</h2>
<p>メールアドレス：<%= @user.email %></p>
<p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to '新規作成', new_task_path %></button></p>
<p class="btn_area"><button type="button" class="btn btn-default btn-default active"><%= link_to 'タスク一覧', tasks_path %></button></p>